### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by officialasit** [georgk10/BinanceTriArb#4]
Hi @georgk10 ,

Just wanted to ask does this project still work as of now (July 2021)?

Thanks

**Comment by georgk10** [comment]
Hey,

The project is not actively maintained and is not expected to trade
profitably. It might still work from a technical point of view, though.


Am Sa., 31. Juli 2021 um 09:42 Uhr schrieb Asit ***@***.***>:

**Comment by KamolovFarrux2005** [comment]
hello Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run   
    self._target(*self._args, **self._kwargs)
  File "c:\Users\User\Desktop\BinanceTriArb\bnArb.py", line 73, in get_rates
    arbitrage = a/x*x/y*y/b
ZeroDivisionError: float division by zero

**Comment by Harukvitalii** [comment]
> hello Exception in thread Thread-1: Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner self.run() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run self._target(_self._args, **self._kwargs) File "c:\Users\User\Desktop\BinanceTriArb\bnArb.py", line 73, in get_rates arbitrage = a/x_x/y*y/b ZeroDivisionError: float division by zero

you need to add precision to pair BTCUSDT in __init__  function to remove this problem

**Comment by Mihaug** [comment]
> you need to add precision to pair BTCUSDT in __init__  function to remove this problem


Please how exactly does one do this? Am getting the exact same error
